# Generated by Django 3.0.5 on 2021-03-10 04:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghazals',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ghazal_name', models.TextField(blank=True, max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('ghazal_content', models.TextField(blank=True, max_length=500)),
                ('author_alphabet', models.CharField(blank=True, max_length=1)),
                ('word_count', models.IntegerField(blank=True)),
                ('cleaned_content', models.TextField(blank=True, max_length=500)),
                ('cleaned_wordcount', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['author_alphabet'],
            },
        ),
    ]
