# Generated by Django 3.0.5 on 2021-03-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghazals',
            options={},
        ),
    ]
